### ISSUE TITLE
Polls necessary

### ISSUE THREAD

**Issue by Tamriel** [takeflight/wagtailpolls#1]
Your app works as expected. Thank you very much! :smiley: 

However, you should mention that it is absolutely necessary to create a poll and add it to a page. If one does not and accesses that page, an exception will be raised.

Therefore you should add an if clause around the template:

```
{% if self.poll %}
    <form class='poll' method='POST' action='{% vote self.poll %}'>
        {% csrf_token %}
        {{ self.poll.form }}
        <br><br>
        <input type="submit" value="Vote">
    </form>
{% else %}
    No polls added to this page yet!
{% endif %}
```

Furthermore, your link to documentation in the README returns 404. Remove it?

**Comment by LiamBrenner** [comment]
Thanks @Tamriel, I have since made some changes to fix the above! :)
