### ISSUE TITLE
Vote requires auth

### ISSUE THREAD

**Issue by frague59** [takeflight/wagtailpolls#13]
I'm not logged-in my wagtail application.

The poll us dispalyed (on my home page), and I'm trying to vote on a poll.

The form post returns a log-in form (with 401 I think).

Is it a way to avoid this ? I'ld like to allow voting to un-authenticated users.

Thanks !

**Comment by LiamBrenner** [comment]
Hi Francis,

You'll need to import `from wagtailpolls.views.vote import vote` and include ` url(r'^vote/(?P<poll_pk>.*)/$', vote, name='wagtailpolls_vote')` in your `urls.py`. The latest release (0.3.0) forces you to do this.
