### ISSUE TITLE
ImportError: No module named views

### ISSUE THREAD

**Issue by frague59** [takeflight/wagtailpolls#3]
I'm unable to use the application, because of import error: 

```
File ".../virtualenv/local/lib/python2.7/site-packages/wagtailpolls/urls.py", line 4, in <module>
    from .views import chooser, editor, results, vote
ImportError: No module named views
```

The `views` module is not in the distribution at all, despite of it inclusion in the urls...

**Comment by LiamBrenner** [comment]
This was fixed earlier, but the newest release didn't include the fix! I've now released `0.1.4` which includes the fix. :)
